# Generated by Django 2.0.4 on 2018-04-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('toy_image', models.ImageField(upload_to='toy/%Y/%m/%d')),
                ('tech_stack', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('desc', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('idate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'toy',
                'ordering': ['idate'],
            },
        ),
    ]
