# Generated by Django 2.0.4 on 2018-04-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0002_auto_20180419_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tech_stack',
            },
        ),
        migrations.RemoveField(
            model_name='toy',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='toy',
            name='tech_stack',
            field=models.ManyToManyField(related_name='toy_techstack_set', to='toy.TechStack'),
        ),
    ]
