# Generated by Django 2.0.4 on 2018-04-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0003_auto_20180419_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, null=True, related_name='toy_techstack_set', to='toy.TechStack'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='toy_image',
            field=models.ImageField(blank=True, null=True, upload_to='toy/%Y/%m/%d'),
        ),
    ]
