# Generated by Django 2.0.4 on 2018-04-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codelab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='대표이미지를 선택해주세요.', upload_to='codelab/%Y/%m/%d')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('desc', models.CharField(max_length=200)),
                ('favorite', models.IntegerField(default=0)),
                ('isview', models.BooleanField(default=True)),
                ('idate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'codelab',
                'ordering': ['-idate'],
            },
        ),
        migrations.CreateModel(
            name='CodelabDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('idate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('codelab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codelab_codelab_set', to='codelab.Codelab')),
            ],
            options={
                'db_table': 'codelab_detail',
                'ordering': ('-codelab',),
            },
        ),
    ]
