# Generated by Django 2.0.4 on 2018-04-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelab', '0003_auto_20180417_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='codelabdetail',
            name='user_email',
            field=models.EmailField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codelabdetail',
            name='user_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codelabdetail',
            name='user_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
