# Generated by Django 2.0.4 on 2018-04-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelab', '0004_auto_20180420_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='codelabdetail',
            name='contents_markdown',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
