# Generated by Django 2.0.4 on 2018-04-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelab', '0005_codelabdetail_contents_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelab',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='codelabdetail',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
