# Generated by Django 2.0.4 on 2018-04-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelab', '0007_auto_20180427_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelab',
            name='image',
            field=models.ImageField(help_text='대표이미지를 선택해주세요.', upload_to='codelab/%Y/%m/%d'),
        ),
    ]
